name: kutalo-links

services:
  links-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kutalo-links-php
    restart: unless-stopped
    volumes:
      - ./backend/.env:/var/www/html/.env
      - ./backend/storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - kutalo-appnet
    labels:
      traefik.enable: "false"

  links-nginx:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: kutalo-links-nginx
    restart: unless-stopped
    depends_on:
      - links-php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - kutalo-appnet
    labels:
      traefik.enable: "false"

networks:
  kutalo-appnet:
    external: true
    name: kutalo-appnet
