services:
  links-php:
    volumes:
      - ./backend/app:/var/www/html/app
      - ./backend/bootstrap/app.php:/var/www/html/bootstrap/app.php
      - ./backend/bootstrap/providers.php:/var/www/html/bootstrap/providers.php
      - ./backend/config:/var/www/html/config
      - ./backend/database:/var/www/html/database
      - ./backend/resources:/var/www/html/resources
      - ./backend/routes:/var/www/html/routes
      - ./backend/artisan:/var/www/html/artisan
      - ./docker/php/opcache-live-code.ini:/usr/local/etc/php/conf.d/zz-opcache-live-code.ini:ro

  links-nginx:
    labels:
      traefik.enable: "true"
      traefik.http.routers.links.rule: "Host(`l.kutalo.com`)"
      traefik.http.routers.links.entrypoints: "websecure"
      traefik.http.routers.links.tls.certresolver: "letsencrypt"
      traefik.http.routers.links.middlewares: "laravel-security@file"
      traefik.http.services.links.loadbalancer.server.port: "80"
